/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    IconCarbonAdd: typeof import('~icons/carbon/add')['default']
    IconCarbonAppConnectivity: typeof import('~icons/carbon/app-connectivity')['default']
    IconCarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    IconCarbonAttachment: typeof import('~icons/carbon/attachment')['default']
    IconCarbonBot: typeof import('~icons/carbon/bot')['default']
    IconCarbonChat: typeof import('~icons/carbon/chat')['default']
    IconCarbonChatBot: typeof import('~icons/carbon/chat-bot')['default']
    IconCarbonChatOff: typeof import('~icons/carbon/chat-off')['default']
    IconCarbonClean: typeof import('~icons/carbon/clean')['default']
    IconCarbonClose: typeof import('~icons/carbon/close')['default']
    IconCarbonCopy: typeof import('~icons/carbon/copy')['default']
    IconCarbonDocument: typeof import('~icons/carbon/document')['default']
    IconCarbonDocumentBlank: typeof import('~icons/carbon/document-blank')['default']
    IconCarbonEducation: typeof import('~icons/carbon/education')['default']
    IconCarbonIdea: typeof import('~icons/carbon/idea')['default']
    IconCarbonInformation: typeof import('~icons/carbon/information')['default']
    IconCarbonList: typeof import('~icons/carbon/list')['default']
    IconCarbonMenu: typeof import('~icons/carbon/menu')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonScreen: typeof import('~icons/carbon/screen')['default']
    IconCarbonSearch: typeof import('~icons/carbon/search')['default']
    IconCarbonSecurity: typeof import('~icons/carbon/security')['default']
    IconCarbonSend: typeof import('~icons/carbon/send')['default']
    IconCarbonSettings: typeof import('~icons/carbon/settings')['default']
    IconCarbonSettingsAdjust: typeof import('~icons/carbon/settings-adjust')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconCarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    IconCarbonView: typeof import('~icons/carbon/view')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
